name: Validate Cocktail Data

on: [push, pull_request]

jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "18"

            - name: Install dependencies
              run: npm install

            - name: Validate JSON schemas
              run: npm run validate

            - name: Check file structure
              run: |
                  for base_file in data/base/*.json; do
                    filename=$(basename "$base_file" .json)
                    if [ ! -f "data/translations/en/$filename.json" ]; then
                      echo "Missing English translation for $filename"
                      exit 1
                    fi
                    if [ ! -f "data/translations/de/$filename.json" ]; then
                      echo "Missing German translation for $filename"
                      exit 1
                    fi
                  done
